databases:
  - name: members
    plan: free
    databaseName: members_39ci
    user: members_39ci_user

services:
  - type: web
    plan: free
    name: remoteguru_backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn remoteguru_backend.asgi:application -k uvicorn.workers.UvicornWorker"
      - key: DATABASE_URL
        fromDatabase:
          name: remoteguru_backend_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
